### ISSUE TITLE
X-RateLimit

### ISSUE THREAD

**Issue by sm2017** [dex4er/js-sliding-window-rate-limiter#10]
How can I calculate X-RateLimit-Remaining and X-RateLimit-Reset ?

**Comment by dex4er** [comment]
Do you want to implements something like https://stackoverflow.com/questions/16022624/examples-of-http-api-rate-limiting-http-response-headers ?

So `Remaining` seems to be easy: it is 

```js
remaining = limit - usage
```

Reset might be tricky because this is **sliding**window** limiter, not fixed window, so remaining time is variable. If it would be possible to implement it in Lua then I could add additional operation to Redis Lua script and then method to the library.

**Comment by dex4er** [comment]
I think I have an idea:

I can do

```redis
ZRANGEBYSCORE key -inf +inf WITHSCORES LIMIT ${usage - limit} 1
```

to get a last timestamp and then current timestamp minus last timestamp is a number of milliseconds to wait.

so probably it would be possible it implement it.

**Comment by dex4er** [comment]
New v3 version enchanced API and now limiter returns `reset` property with a time (ms) when another reservation will be possible.
