### ISSUE TITLE
why did you drop node 6?

### ISSUE THREAD

**Issue by regevbr** [dex4er/js-sliding-window-rate-limiter#8]
why did you drop node 6?
Sadly I'm still using it...
@dex4er  Can you please revert or should I just fork it?

**Comment by regevbr** [comment]
Also this is a breaking change thus you need to increase the version to 2 (semver way)

**Comment by dex4er** [comment]
Ok. I'll revert it in 1.x.x and then later will use it 2.x.x so you can stay with 1.x.x for your project.

I'm sorry for trouble.

**Comment by dex4er** [comment]
Fixed in v1.5.0

New v2.0.0 will be with ES2017 support only, but... you can still use new versions. Just transpile to ES6 target as it is now described in README. Unfortunately you would have to use `esModuleInterop` but it works and that way I use ES6 or ES7 modules with ES5 target.

BTW, Node 6 will have end-of-line very soon.
